example:
  property: I AM THE DEFAULT

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2-console
  cloud:
    stream:
      bindings:
        output:
          destination: orgChangeTopic # 메시지를 작성할 큐 이름
          content-type: application/json # 송수신할 메시지 타입
      kafka:
        binder:
          zkNodes: localhost:9092
          brokers: localhost:9092
  kafka:
    bootstrap:
      servers: localhost:9092

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    preferIpAddress: true #서비스 이름 대신 IP 주소 등록
  client:
    registerWithEureka: true # 유레카 서비스 등록 여부
    fetchRegistry: true # 레지스트리 사본을 로컬에 내려받기
    serviceUrl:
      defaultZone: http://localhost:8070/eureka # 유레카 서비스의 위치 설정