version: '3'

services:
  licensingservice:
    image: ostock/licensing-service:0.0.2-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: "default"
      SPRING_CLOUD_CONFIG_URI: "http://localhost:8071"