# Generated by Django 2.2.2 on 2019-06-18 06:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_auto_20190618_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_boards', to=settings.AUTH_USER_MODEL),
        ),
    ]
