spring:
  application:
    name: config-server
  profiles:
    active: native #, git, vault
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config # 파일시스템 컨피그 경로

server:
  port: 8071

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    circuitbreakers:
      enabled: true